# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-22 09:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
    ]
