# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-20 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_auto_20190520_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
