# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_auto_20190520_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('date_posted',)},
        ),
    ]
