# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-21 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0007_auto_20190521_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='date_posted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
